variables:
  SERVER_IP1: 172.16.191.44
  SERVER_IP2: 172.16.191.45
  BUILD_LOCATION: "/app/assetlite/src/projects_uat/gitlab_uat"
stages:
  - uat_backup
  - clone
  - build
  - deploy
  - svc-restart

.job_template: &template
    tags:
      - bl-devops
    
tar_backup:
  <<: *template
  variables:
    data_location: "/app/asset_lite_prd/www/bl_assetelite_api"
  stage: uat_backup
  #needs: [CI_Pre-check]
  when: manual
  # rules:
  #   - if: ($CI_COMMIT_BRANCH == "develop" || $NPM_VERSION == "$NPM_VERSION")
  script:
    - echo "Starting backup"
    - sh /app/script/bl_assetlite_bk.sh
    #- ssh usrdev@$SERVER_IP tar czf - /app/asset_lite_prd/www/bl_assetelite_api > /app/backup/"$CI_PROJECT_NAME"_"$CI_PIPELINE_IID"_`date +"%d-%m-%Y-%H:%M:%S"`.tar.gz

release_uat_repo_clone:
  <<: *template
  stage: clone
#   only:
#     - main
  when: manual
  variables:
    BRANCH: release-uat-22
  script:
    - echo "Clonging repo"
    #- git branch
    #- cd $STG_BUILD_LOCATION
    #- sudo git clone -b $BRANCH https://$MYUSERNAME:$MYTOKEN@gitlab.com/techbeach1/mybl-qa.git
    - cd $BUILD_LOCATION/$CI_PROJECT_NAME
    #- sudo git checkout develop
    - git pull origin $BRANCH

deploy_release_uat_22:
  <<: *template
  variables:
    DEST_PATH: "/app/asset_lite_prd/www/bl_assetelite_api"
  stage: deploy
  when: manual
  # rules:
  #   - if: ($CI_COMMIT_BRANCH == "develop" || $NPM_VERSION == "$NPM_VERSION")
  before_script:
    - eval $(ssh-agent -s)
  script:
    - echo "Copying build artifacts to live server"
    - ssh-add <(echo "$KEY_STAGING")
    #- rsync -avzt $BUILD_LOCATION/$CI_PROJECT_NAME/$SOURCE/ bs1048@192.168.56.1:$path_1/$DEST
    - rsync -avzt $BUILD_LOCATION/$CI_PROJECT_NAME/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .gitignore --exclude .gitattributes usrdev@$SERVER_IP1:$DEST_PATH
    - rsync -avzt $BUILD_LOCATION/$CI_PROJECT_NAME/ --exclude .git/ --exclude .gitlab-ci.yml --exclude .gitignore --exclude .gitattributes usrdev@$SERVER_IP2:$DEST_PATH

service_restart:
  stage: svc-restart
  variables:
    ANSIBLE_PATH: "/app/mybl/ansible/ansible-mybl-app-deploy/ENV/PROD/WEB-API"
  when: manual
  tags:
    - bl-web-api
  script:
    #- echo $ANSIBLE_PATH
    #- cp -r /home/usrdev/config /home/usrdev/builds/BErMj8E2/0/bl-front/bl-web-frontend/.git/config
    - cd $ANSIBLE_PATH && ansible-playbook service-manage.yml
    - echo 1>/app/mybl/runner/stdout
